package components

// builtinCatalog returns the curated list of components that ship with knaic.
// The frontend mirrors this list — keep them in sync.
func builtinCatalog() []Component {
	return []Component{
		{
			Name:            "kserve",
			DisplayName:     "KServe",
			Description:     "Standard model inference platform on Kubernetes with LLMInferenceService support.",
			Category:        CategoryInference,
			Versions:        []string{"v0.13.0", "v0.14.0", "v0.15.1"},
			SelectedVersion: "v0.14.0",
			Status:          StatusNotInstalled,
			Images:          []string{"kserve/kserve-controller:v0.14.0", "kserve/models-web-app:v0.14.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
			Embedded:        true,
		},
		{
			Name:            "hami",
			DisplayName:     "HAMi",
			Description:     "Heterogeneous AI computing virtualization — GPU/NPU sharing scheduler.",
			Category:        CategoryGPU,
			Versions:        []string{"v2.3.11", "v2.4.0"},
			SelectedVersion: "v2.4.0",
			Status:          StatusNotInstalled,
			Images:          []string{"projecthami/hami:v2.4.0", "projecthami/hami-scheduler:v2.4.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "nvidia-device-plugin",
			DisplayName:     "NVIDIA GPU Device Plugin",
			Description:     "Exposes NVIDIA GPUs as schedulable resources on each node.",
			Category:        CategoryGPU,
			Versions:        []string{"v0.14.5", "v0.15.0", "v0.17.0"},
			SelectedVersion: "v0.17.0",
			Status:          StatusNotInstalled,
			Images:          []string{"nvcr.io/nvidia/k8s-device-plugin:v0.17.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "kf-notebook-controller",
			DisplayName:     "Kubeflow Notebook Controller",
			Description:     "Creates and manages Jupyter notebook servers as Kubernetes resources.",
			Category:        CategoryNotebook,
			Versions:        []string{"v1.9.0", "v1.10.0"},
			SelectedVersion: "v1.10.0",
			Status:          StatusNotInstalled,
			Images:          []string{"ghcr.io/kubeflow/kubeflow/notebook-controller:v1.10.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "kf-trainer-v2",
			DisplayName:     "Kubeflow Trainer v2",
			Description:     "Next-generation Kubernetes training operator for LLM fine-tuning.",
			Category:        CategoryTraining,
			Versions:        []string{"v2.0.0-rc.0", "v2.0.0"},
			SelectedVersion: "v2.0.0",
			Status:          StatusNotInstalled,
			Images:          []string{"kubeflow/trainer-controller-manager:v2.0.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "envoy-gateway",
			DisplayName:     "Envoy Gateway",
			Description:     "Kubernetes-native Envoy Gateway implementation.",
			Category:        CategoryNetworking,
			Versions:        []string{"v1.2.1", "v1.3.0"},
			SelectedVersion: "v1.3.0",
			Status:          StatusNotInstalled,
			Images:          []string{"envoyproxy/gateway:v1.3.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "envoy-ai-gateway",
			DisplayName:     "Envoy AI Gateway",
			Description:     "LLM-aware routing, rate limiting and token quota on top of Envoy Gateway.",
			Category:        CategoryNetworking,
			Versions:        []string{"v0.2.0", "v0.3.0"},
			SelectedVersion: "v0.3.0",
			Status:          StatusNotInstalled,
			Images:          []string{"envoyproxy/ai-gateway:v0.3.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "lws",
			DisplayName:     "LeaderWorkerSet (LWS)",
			Description:     "Multi-host inference / training group scheduling primitive.",
			Category:        CategoryInference,
			Versions:        []string{"v0.4.1", "v0.5.0"},
			SelectedVersion: "v0.5.0",
			Status:          StatusNotInstalled,
			Images:          []string{"registry.k8s.io/lws/lws:v0.5.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "jobset",
			DisplayName:     "JobSet",
			Description:     "Groups multiple Jobs into a single logical unit for distributed workloads.",
			Category:        CategoryScheduling,
			Versions:        []string{"v0.6.0", "v0.7.2"},
			SelectedVersion: "v0.7.2",
			Status:          StatusNotInstalled,
			Images:          []string{"registry.k8s.io/jobset/jobset:v0.7.2"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "prometheus",
			DisplayName:     "Prometheus",
			Description:     "Metrics collection and storage — powers the monitoring dashboards.",
			Category:        CategoryObservability,
			Versions:        []string{"v2.54.0", "v2.55.0", "v3.0.0"},
			SelectedVersion: "v2.55.0",
			Status:          StatusNotInstalled,
			Images:          []string{"prom/prometheus:v2.55.0", "prom/node-exporter:v1.8.2"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
		{
			Name:            "mlflow",
			DisplayName:     "MLflow",
			Description:     "Experiment tracking and model registry. Used by TrainJobs to report metrics.",
			Category:        CategoryExperiment,
			Versions:        []string{"v2.16.2", "v2.17.1", "v2.18.0"},
			SelectedVersion: "v2.18.0",
			Status:          StatusNotInstalled,
			Images:          []string{"ghcr.io/mlflow/mlflow:v2.18.0"},
			ImageSync:       SyncPending,
			Builtin:         true,
		},
	}
}
