export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string;
}

interface StreamOpts {
  model: string;
  temperature: number;
  system: string;
  history: ChatMessage[];
}

function craftReply(opts: StreamOpts): string {
  const user = [...opts.history].reverse().find(m => m.role === 'user')?.content ?? '';
  const q = user.toLowerCase();

  if (q.includes('hello') || q.includes('hi')) {
    return `Hi! I'm running via ${opts.model} on your knaic cluster. Ask me anything about your workloads or AI work.`;
  }
  if (q.includes('kubernetes') || q.includes('k8s')) {
    return `Kubernetes is the container orchestration system knaic is built on top of. knaic uses CRDs such as **InferenceService**, **TrainJob** and **Notebook** to represent AI workloads natively.`;
  }
  if (q.includes('train')) {
    return `To start a training job, go to *Training → TrainJobs → New train job*, pick a **TrainingRuntime** and point it at your dataset URI. The Kubeflow Trainer v2 controller will reconcile the rest.`;
  }
  if (q.includes('serve') || q.includes('inference')) {
    return `Open *Inference → Inference services → New inference service*, choose vLLM or SGLang as the runtime, and select a model from the Model Hub. KServe will provision pods, a Service and an ingress route.`;
  }
  if (q.includes('gpu')) {
    return `GPU scheduling is handled by the **HAMi** component plus the **nvidia-device-plugin**. You can monitor per-node GPU utilization under *Resource monitoring*.`;
  }
  return `I hear you: "${user.slice(0, 160)}${user.length > 160 ? '…' : ''}".

Here's what I'd do:
1. Check whether any relevant **InferenceService** is in \`Ready\` state.
2. Inspect its logs from *Inference services → Logs*.
3. If the model isn't loading, verify the storage URI in the Model Hub.

(This response is generated by a local mock, not a real LLM — wire up a real provider under *Playground → LLM Registry* to chat with live models.)`;
}

export function streamResponse(
  opts: StreamOpts,
  onChunk: (c: string) => void,
  onDone: () => void,
): () => void {
  const text = craftReply(opts);
  const tokens = text.match(/\S+\s*|\s+/g) ?? [text];
  let i = 0;
  let cancelled = false;
  const tick = () => {
    if (cancelled) return;
    if (i >= tokens.length) {
      onDone();
      return;
    }
    onChunk(tokens[i]);
    i++;
    window.setTimeout(tick, 30 + Math.random() * 40);
  };
  window.setTimeout(tick, 150);
  return () => {
    cancelled = true;
    onDone();
  };
}

export async function* agentStream(opts: StreamOpts): AsyncGenerator<
  { kind: 'thought' | 'action' | 'observation' | 'final'; text: string }
> {
  const user = [...opts.history].reverse().find(m => m.role === 'user')?.content ?? '';
  const q = user.toLowerCase();

  await sleep(400);
  yield { kind: 'thought', text: `The user is asking: "${user}". I should plan which tool(s) to call.` };
  await sleep(500);

  if (q.includes('pod') || q.includes('deployment') || q.includes('running') || q.includes('status')) {
    yield { kind: 'action', text: `tool: kubectl_list\ninput: {"resource":"pods","namespace":"team-ml"}` };
    await sleep(700);
    yield {
      kind: 'observation',
      text: `NAME                       READY   STATUS    RESTARTS   AGE\nqwen3-5-7b-abcde          2/2     Running   0          3d\nbge-embed-klmno           1/1     Running   1          12h\nhelpdesk-agent-xyzab      0/1     CrashLoop 7          4m`,
    };
    await sleep(600);
    yield {
      kind: 'thought',
      text: `One pod is in CrashLoopBackOff. I should fetch its logs to diagnose.`,
    };
    yield {
      kind: 'action',
      text: `tool: kubectl_logs\ninput: {"pod":"helpdesk-agent-xyzab","container":"agent","tail":50}`,
    };
    await sleep(700);
    yield {
      kind: 'observation',
      text: `[ERROR] failed to connect to postgres: dial tcp 10.0.17.3:5432: connect: connection refused\n[ERROR] shutting down`,
    };
    await sleep(500);
    yield {
      kind: 'final',
      text: `The **helpdesk-agent** pod is crashing because it can't reach Postgres (connection refused to 10.0.17.3:5432).\n\nChecklist:\n- Verify the **postgres-knaic** StatefulSet is Running.\n- Check the Service endpoints match the Pod IP.\n- If Postgres was restarted, the Pod IP has changed — reference the Service DNS name instead.`,
    };
    return;
  }

  if (q.includes('model')) {
    yield { kind: 'action', text: `tool: model_hub_search\ninput: {"query":"qwen"}` };
    await sleep(500);
    yield {
      kind: 'observation',
      text: `Found 2 models:\n- Qwen/Qwen3.5-7B-Instruct (public, 15.2 GiB)\n- Qwen/Qwen3.5-72B-Instruct (public, 146 GiB)`,
    };
    await sleep(400);
    yield {
      kind: 'final',
      text: `Two Qwen models are registered in the public space. For your 8×A100 node, **Qwen3.5-72B-Instruct** fits with tensor parallel 8; for single-GPU serving use the 7B variant.`,
    };
    return;
  }

  yield { kind: 'action', text: `tool: noop\ninput: {}` };
  await sleep(300);
  yield { kind: 'observation', text: `no tool matched — answering from priors` };
  await sleep(300);
  yield {
    kind: 'final',
    text: `I don't have a tool that matches the question, so here's a direct answer based on priors: **knaic** is a console for managing AI workloads on Kubernetes. Ask me about pods, inference services, models, or GPUs and I'll dispatch a tool call.`,
  };
}

function sleep(ms: number) {
  return new Promise(r => window.setTimeout(r, ms));
}
